create table public.exam_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('practice', 'exam')),
  total_questions integer not null check (total_questions >= 0),
  answered_questions integer not null check (answered_questions between 0 and total_questions),
  correct_answers integer not null check (correct_answers between 0 and total_questions),
  started_at timestamptz not null,
  completed_at timestamptz not null default now()
);

alter table public.exam_attempts enable row level security;

create policy "Users manage their own attempts"
on public.exam_attempts
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index exam_attempts_user_id_idx on public.exam_attempts (user_id);
