begin;

create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('practice', 'exam')),
  total_questions integer not null check (total_questions >= 0),
  answered_questions integer not null check (answered_questions between 0 and total_questions),
  correct_answers integer not null check (correct_answers between 0 and total_questions),
  started_at timestamptz not null,
  completed_at timestamptz not null default now()
);

alter table public.exam_attempts
add column if not exists identity_email text
check (identity_email = lower(identity_email) and identity_email ~ '^[^@]+@algorims\.com$');

update public.exam_attempts attempt
set identity_email = lower(coalesce(nullif(app_user.email, ''), app_user.raw_user_meta_data->>'email'))
from auth.users app_user
where attempt.user_id = app_user.id
  and attempt.identity_email is null
  and lower(coalesce(nullif(app_user.email, ''), app_user.raw_user_meta_data->>'email')) ~ '^[^@]+@algorims\.com$';

alter table public.exam_attempts enable row level security;

drop policy if exists "Users manage their own attempts" on public.exam_attempts;
drop policy if exists "Email identities read their attempts" on public.exam_attempts;
drop policy if exists "Email identities create attempts" on public.exam_attempts;

create policy "Email identities read their attempts"
on public.exam_attempts
for select
to authenticated
using (identity_email = lower((select auth.jwt()->'user_metadata'->>'email')));

create policy "Email identities create attempts"
on public.exam_attempts
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and identity_email = lower((select auth.jwt()->'user_metadata'->>'email'))
);

create index if not exists exam_attempts_user_id_idx on public.exam_attempts (user_id);
create index if not exists exam_attempts_identity_email_idx on public.exam_attempts (identity_email);

commit;
